# Generated by Django 5.0.10 on 2025-02-17 17:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminAPIKeys",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hashed_key", models.CharField(db_index=True, max_length=64)),
                (
                    "date_issued",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
