# Generated by Django 5.0.10 on 2025-02-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("railways", "0002_generate_initial_admin_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=30)),
                ("auth_token", models.CharField(blank=True, max_length=64, null=True)),
                ("token_issued", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["email", "password"], name="email_pass_index")
                ],
            },
        ),
    ]
