# Generated by Django 5.0.10 on 2025-02-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("railways", "0003_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminapikeys",
            name="hashed_key",
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
