# Generated by Django 5.0.10 on 2025-02-17 17:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("railways", "0004_alter_adminapikeys_hashed_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="Train",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.PositiveIntegerField()),
                ("destination", models.PositiveIntegerField()),
                ("seats", models.PositiveIntegerField()),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["source", "destination"],
                        name="source_destination_index",
                    )
                ],
            },
        ),
    ]
