# Generated by Django 5.0.10 on 2025-02-17 19:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("railways", "0005_train"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bookings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.PositiveIntegerField()),
                ("destination", models.PositiveIntegerField()),
                ("seats", models.PositiveIntegerField()),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "train",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="railways.train"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="railways.user"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user"], name="user_id_index"),
                    models.Index(fields=["train"], name="train_id_index"),
                    models.Index(
                        fields=["train", "source", "destination"],
                        name="train_source_dest_index",
                    ),
                ],
            },
        ),
    ]
