# Generated by Django 5.0.10 on 2025-02-18 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("railways", "0006_bookings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="auth_token",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
