# Generated by Django 5.0.10 on 2025-02-18 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("railways", "0007_alter_user_auth_token"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="bookings",
            index=models.Index(fields=["id", "user"], name="book_id_user_index"),
        ),
    ]
