# Generated by Django 5.0.10 on 2025-02-18 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("railways", "0008_bookings_book_id_user_index"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="train",
            index=models.Index(fields=["id"], name="trains_id_index"),
        ),
    ]
