# Generated by Django 5.1.6 on 2025-02-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("railways", "0009_train_trains_id_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookings",
            name="status",
            field=models.IntegerField(null=True),
        ),
    ]
